# Generated by Django 5.2.10 on 2026-01-21 09:13

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Subject',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
                ('code', models.CharField(max_length=10, unique=True)),
                ('description', models.TextField(blank=True)),
            ],
            options={
                'verbose_name_plural': 'Subjects',
            },
        ),
        migrations.CreateModel(
            name='Class',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('code', models.CharField(max_length=10, unique=True)),
                ('level', models.IntegerField()),
                ('section', models.CharField(blank=True, max_length=1)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('subjects', models.ManyToManyField(related_name='classes', to='academic.subject')),
            ],
            options={
                'verbose_name_plural': 'Classes',
                'unique_together': {('level', 'section')},
            },
        ),
    ]
